#!/usr/bin/env bash

set -euo pipefail

echo "Проверка базовых файлов..."

if [ ! -f "composer.json" ]; then
    echo "❌ Файл composer.json не найден"
    exit 1
fi

if [ ! -f "Makefile" ]; then
    echo "❌ Файл Makefile не найден"
    exit 1
fi

if [ ! -d "vendor" ]; then
    echo "❌ Директория vendor не найдена. Выполни composer install"
    exit 1
fi

if [ ! -f ".env" ]; then
    echo "❌ Файл .env не найден"
    exit 1
fi

echo "✅ Базовые проверки пройдены"
